

### MIRAGE REALMS ###
## ASSETS
## WINDOWS
FULL_HD_RESOLUTION = [1920,1080]
WINDOW_TITLE = 'Mirage Realms - Early'
WINDOW_HALF_SIZE = []
WINDOW_ONE_THIRD_SIZE = [583,509]
## FONTS
FONTS_DEFAULT_FAMILY = "calibri"
FONTS_DEFAULT_SIZE = "10"
## SPELLS
## SPOTS
## HEALTH / MANA (HM)
